/*### 1. SELECT: Get only Customer Names and Emails
POST http://localhost:4004/odata/v4/catalog/customers?$select=name,email
Content-Type: application/json
{
  "name": "Tarun",
  "email": "tarun@gmail.com"
}

### CREATE Customer 2
POST http://localhost:4004/odata/v4/catalog/customers
Content-Type: application/json
{
  "name": "Deloitte Recruiter",
  "email": "hiring@deloitte.com"
}

### Select
GET http://localhost:4004/odata/v4/catalog/customers?$select=name,email

### FILTER: Find Tarun
GET http://localhost:4004/odata/v4/catalog/customers?$filter=name eq 'Tarun'

### FILTER: Open Tickets
GET http://localhost:4004/odata/v4/catalog/SupportTickets?$filter=status eq 'Open'

### CREATE Customer WITH Tickets (Auto-Link)
POST http://localhost:4004/odata/v4/catalog/customers
Content-Type: application/json
//give me everything about customers and tickets just using expand only
{
  "name": "Tarun",
  "email": "tarun@gmail.com",
  "tickets": [
    {
      "issue": "Login Issue",
      "status": "Open"
    },
    {
      "issue": "Payment Failed",
      "status": "Open"
    }
  ]
}
###
GET http://localhost:4004/odata/v4/catalog/customers?$expand=tickets

###
GET http://localhost:4004/odata/v4/catalog/customers?$select=name&expand=tickets
*/



### Test Placement Logic: Amit (GPA 6.8) applying to SAP (Min GPA 7.5)
POST http://localhost:4004/odata/v4/catalog/JobApplications
Content-Type: application/json

{
    "ID": "f47ac10b-58cc-4372-a567-0e02b2c3d999",
    "student_ID": 3,
    "company_ID": 2,
    "application_status": "Applied"
}

### Get Student IDs
GET http://localhost:4004/odata/v4/catalog/Students

### Get Company IDs
GET http://localhost:4004/odata/v4/catalog/Companies

### Test Placement Logic: Amit (GPA 6.8) applying to SAP (Min GPA 7.5)
POST http://localhost:4004/odata/v4/catalog/JobApplications
Content-Type: application/json

{
    "student_ID": 3,
    "company_ID": 2,
    "application_status": "Applied"
}
