### 1. SELECT: Get only Customer Names and Emails
POST http://localhost:4004/odata/v4/catalog/customers?$select=name,email
Content-Type: application/json
{
  "name": "Tarun",
  "email": "tarun@gmail.com"
}

### CREATE Customer 2
POST http://localhost:4004/odata/v4/catalog/customers
Content-Type: application/json
{
  "name": "Deloitte Recruiter",
  "email": "hiring@deloitte.com"
}

### Select
GET http://localhost:4004/odata/v4/catalog/customers?$select=name,email

### FILTER: Find Tarun
GET http://localhost:4004/odata/v4/catalog/customers?$filter=name eq 'Tarun'

### FILTER: Open Tickets
GET http://localhost:4004/odata/v4/catalog/SupportTickets?$filter=status eq 'Open'

### CREATE Customer WITH Tickets (Auto-Link)
POST http://localhost:4004/odata/v4/catalog/customers
Content-Type: application/json
//give me everything about customers and tickets just using expand only
{
  "name": "Tarun",
  "email": "tarun@gmail.com",
  "tickets": [
    {
      "issue": "Login Issue",
      "status": "Open"
    },
    {
      "issue": "Payment Failed",
      "status": "Open"
    }
  ]
}
###
GET http://localhost:4004/odata/v4/catalog/customers?$expand=tickets

###
GET http://localhost:4004/odata/v4/catalog/customers?$select=name&expand=tickets
